# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basecamp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'basecamp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x61secamp.proto\x12\x08\x62\x61secamp\x1a\x1bgoogle/protobuf/empty.proto\"J\n\tPingReply\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x10\n\x08language\x18\x04 \x01(\t\"?\n\x0cProbeRequest\x12\x11\n\torigin_id\x18\x01 \x01(\t\x12\x0b\n\x03ttl\x18\x02 \x01(\r\x12\x0f\n\x07payload\x18\x03 \x01(\t\"E\n\nProbeReply\x12\x14\n\x0cresponder_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"/\n\x0cNeighborInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\"K\n\rNeighborReply\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12)\n\tneighbors\x18\x02 \x03(\x0b\x32\x16.basecamp.NeighborInfo2\xca\x01\n\x0bNodeService\x12\x35\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x13.basecamp.PingReply\"\x00\x12>\n\x0c\x46orwardProbe\x12\x16.basecamp.ProbeRequest\x1a\x14.basecamp.ProbeReply\"\x00\x12\x44\n\x0fGatherNeighbors\x12\x16.google.protobuf.Empty\x1a\x17.basecamp.NeighborReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basecamp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREPLY']._serialized_start=57
  _globals['_PINGREPLY']._serialized_end=131
  _globals['_PROBEREQUEST']._serialized_start=133
  _globals['_PROBEREQUEST']._serialized_end=196
  _globals['_PROBEREPLY']._serialized_start=198
  _globals['_PROBEREPLY']._serialized_end=267
  _globals['_NEIGHBORINFO']._serialized_start=269
  _globals['_NEIGHBORINFO']._serialized_end=316
  _globals['_NEIGHBORREPLY']._serialized_start=318
  _globals['_NEIGHBORREPLY']._serialized_end=393
  _globals['_NODESERVICE']._serialized_start=396
  _globals['_NODESERVICE']._serialized_end=598
# @@protoc_insertion_point(module_scope)
