node_id=A
language=cpp
listen_host=0.0.0.0
listen_port=50051

# Full 9-node tree config
neighbors=B@127.0.0.1:50052,H@127.0.0.1:50058,G@127.0.0.1:50057,I@127.0.0.1:50059

# 3-node test config: A -> B -> C
#neighbors=B@127.0.0.1:50052

assigned_files=../basic/data/shards/A/yellow_2020_A.csv