node_id=B
language=cpp
listen_host=0.0.0.0
listen_port=50052

# Full tree config
neighbors=C@127.0.0.1:50053,D@127.0.0.1:50054,E@127.0.0.1:50055

# 3-node test config: B -> C
#neighbors=C@127.0.0.1:50053

assigned_files=../basic/data/shards/B/yellow_2020_B.csv