node_id=A
language=cpp
listen_host=0.0.0.0
listen_port=50051

# Full 9-node tree config

neighbors=B@__LAPTOP1_IP__:50052,H@__LAPTOP2_IP__:50058,G@__LAPTOP2_IP__:50057,I@__LAPTOP2_IP__:50059
assigned_files=../basic/data/shards/A/yellow_2020_A.csv